apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-serving-webhook
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: serving-webhook
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
