apiVersion: apps/v1
kind: Deployment
metadata:
  name: serving-webhook
  labels:
    app: serving-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serving-webhook
  template:
    metadata:
      labels:
        app: serving-webhook
    spec:
      containers:
        - name: serving-webhook-container
          image: yangwenz/model-webhook:v2
          imagePullPolicy: Always
          ports:
            - name: control
              containerPort: 12000
          env:
            - name: GIN_MODE
              value: release
            - name: REDIS_ADDRESS
              value: "redis-master:6379"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: webhook-secret
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: webhook-secret
                  key: secret-access-key
          livenessProbe:
            httpGet:
              path: /live
              port: 12000
            initialDelaySeconds: 5
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /ready
              port: 12000
            initialDelaySeconds: 5
            periodSeconds: 20
