apiVersion: v1
kind: Service
metadata:
  name: serving-webhook-service
spec:
  selector:
    app: serving-webhook
  ports:
    - name: control
      protocol: TCP
      port: 12000
      targetPort: 12000
  type: ClusterIP
